config/routes.rb
Rails.application.routes.draw do

  get 'articles/search' => 'articles#search', as: 'search'
  get "/articles/:id/edit" => "revisions#new"

  resources :users, only: [:new, :create]

  get "categories/:id/articles" => "categories#show"

  mount Ckeditor::Engine => '/ckeditor'
  resources :categories, only: [:index, :show]
  # resources :categories do
  #   resources :articles
  # end
  resources :articles, except: :edit

  root 'welcome#index'
  get '/sessions/new', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/sessions', to: 'sessions#destroy', as: 'logout'

  resources :articles do
    resources :revisions, only: [:index, :new, :create, :show]
  end
end

app/models/article.rb
require 'nokogiri'

class Article < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :revisions

  validates :title, presence: true, uniqueness: true
  validates :author, presence: true

  def categories=(category_ids)
    category_ids.each do |category_id|
      self.categories << Category.find_by(id: category_id)
    end
  end

  def shorten
  	snippet = Nokogiri::HTML::Document.parse(body)
    text = snippet.css('p').map(&:text).pop
    text[0..50] + "..."
  end

  def thumbnail
  	if is_thumbnail?
	  	snippet = Nokogiri::HTML::Document.parse(body)
	  	img_url = snippet.css('img').attr('src').value
  	else false
  	end
  end

  def update_article
    if self.revisions.any?
      self.body = self.revisions.last.body
    end
    self
  end

  def self.search(parameter)
    where("body LIKE ?", "%#{parameter}%")
  end

private
  def is_thumbnail?
  	self.body.include?("img")
  end
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :articles, through: :categorizations
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  belongs_to :article
  belongs_to :author, class_name: "User"

  validates :body, presence: true
  validates :author, presence: true

  def set_author
    self.author = User.create(username: generate_user, password: generate_password)
  end

  private
    def generate_user
      "Guest-" + SecureRandom.hex(3)
    end

    def generate_password
      SecureRandom.hex(10)
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, foreign_key: :author_id
  has_many :revisions, foreign_key: :author_id

  validates :username, :password_digest, presence: true
  validates :username, uniqueness: true

  has_secure_password

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/' unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find_by(id: params[:id])
    @revisions = @article.revisions
    @article.update_article
    p @article.body
  end

  # def edit
  #   @article = Article.find_by(id: params[:id])
  # end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user
    if @article.save
      @revisions = @article.revisions
      render 'show'
    else
      @categories = Category.all
      render 'new'
    end
  end

  def search
    @articles = Article.search(params[:search]).order("created_at DESC")
    render 'results'
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, categories: [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController

  def index
    @article= Article.find(params[:article_id])
    @revisions = Revision.where(article_id: params[:article_id])
  end

  def show
    @revision = Revision.where(article_id: params[:article_id], id: params[:id])
  end

  def new
    @article = Article.find_by(id: params[:id]).update_article
    @revision = Revision.new
  end


  def create
    article = Article.find(params[:article_id])
    @revision = article.revisions.new(revision_params)
    p current_user
    if current_user
      @revision.author = current_user
    else
      @revision.set_author
    end
    if @revision.save
      redirect_to article_path(@revision.article)
    else
      render "new"
    end
  end

  private
  def revision_params
    params.require(:revision).permit(:body, :author)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      if request.xhr?
        redirect_to :back
      else
        redirect_to '/'
      end
    else
      @errors = ['Invalid username or password']
      if request.xhr?
        render partial: 'errors', status: 422
      else
        render 'new'
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :back
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      @errors = user.errors.full_messages
      @user = User.new
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @articles = Article.all
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <%= @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @article do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :body %>
    <%= f.cktext_area :body, rows: 10 %>

    <%= f.label :category %><br>

    <% @categories.each do |category| %>
      <%= check_box_tag("article[categories][]", category.id, false, id: category.name) %>
      <%= category.name %>
    <% end %>

    <%= f.submit %>

<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<p>they're hare-raising!</p>

<ul class='articles-list'>
	<%	@articles.each do |article| %>
		<li id=<%="article-" + "#{article.id}" %> >
			<h3> <%= link_to(article.title, article_path(article.id)) %> </h3>
			<p> <% if article.thumbnail %> <img src="<%=article.thumbnail%>" style="width:100px;height:100px"> <% else %> <img src="https://raw.githubusercontent.com/TylerSmall19/cotton-tales/NoahRGuy-logo/logo.png" style="width:100px;height:100px"> <% end %> <%= article.shorten %> </p>
		</li>
	<% end %>
</ul>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render :partial => 'articles/form' %>

app/views/articles/results.html.erb
<h1>Your Results</h1>

<% if @articles %>
  <ul class='articles-list'>
    <%  @articles.each do |article| %>
      <li id=<%="article-" + "#{article.id}" %> >
        <h3> <%= link_to(article.title, article_path(article.id)) %> </h3>
        <p> <% if article.thumbnail %> <img src="<%=article.thumbnail%>" style="width:100px;height:100px"> <% else %> <img src="https://raw.githubusercontent.com/TylerSmall19/cotton-tales/NoahRGuy-logo/logo.png" style="width:100px;height:100px"> <% end %> <%= article.shorten %> </p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Nothing matches your search results! Have a carrot instead?</p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h3>This article has <%= @revisions.count %> revisions. <%= link_to "History", article_revisions_path(@article) %></h3><br>

<p><%= @article.body.html_safe %></p><br>

<h4>Categories: </h4>
  <ul>
    <% @article.categories.each do |category| %>
    <li><%= link_to "#{category.name}", category_path(category)%></li>
    <% end %>
  </ul>

<div><%= link_to "Edit", edit_article_path(@article) %></div>

app/views/categories/index.html.erb
<h1>All Categories!</h1>
<ol>
  <% if @categories %>
    <% @categories.each do |category| %>
      <strong><li><%= link_to category.name, category_path(category) %></li></strong>
    <%end%>
  <% end %>
</ol>

app/views/categories/show.html.erb
<% if @category %>
  <h1> Category: <%= @category.name %> </h1>
  <% if @category.articles.any? %>
   <ol class="inline recent-articles"> <% @category.articles.each do |article| %>
      <strong><li><p><%= article.title %></p></li></strong>
      <p> <% if article.thumbnail %> <img src="<%=article.thumbnail%>" style="width:100px;height:100px"> <% else %> <img src="https://raw.githubusercontent.com/TylerSmall19/cotton-tales/NoahRGuy-logo/logo.png" style="width:100px;height:100px"> <% end %> <%= article.body.html_safe %></p>
      <p><%= link_to "Show More", article_path(article) %></p>
      <br />
    <%end%>
    </ol>
  <%else%>
    <p>No articles to display</p>
  <%end%>
<%end%>


<p><%= link_to 'All Categories', categories_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Rabbit Hole</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%=  stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Princess+Sofia'%>

  <%= csrf_meta_tags %>
</head>
<body>

  <h1 id="website-title">The Rabbit Hole</h1>
  <div id='nav'>
    <nav> <%= link_to 'Home', root_path %> |
      <% if current_user %>
        <%= link_to 'Logout', logout_path %> |  <%= link_to 'New Bunny Tail', new_article_path %> | <span id='username-nav'>Logged in as <%= current_user.username %></span></nav>
      <% else %>
        <%= link_to 'Register', new_user_path %> |  <%= link_to 'Login', sessions_new_path, id: 'login-link', remote: true %>

        <div id="login-form" style="display:none;"></div></nav>

    <% end %>
</div>

<%= yield %>
<footer>
  <%= link_to 'created by Team Time', 'https://github.com/TylerSmall19/cotton-tales' %><span id="tm">&trade;</span>
</footer>
</body>

</html>

app/views/revisions/index.html.erb
<h1>All Revisions of <%=@article.title%></h1>
<p><%= @revisions.count%> revisions</p>

<ul class='articles-list'>
  <%  @revisions.each do |revision| %>
    <li id=<%="revision-" + "#{revision.id}" %> >
      <%=revision.body.html_safe%>
      <%=revision.author.username%>
    </li>
  <% end %>
</ul>

app/views/revisions/new.html.erb
<%= form_for [@article, @revision] do |f| %>
  <%= f.label :body %><br />
  <%= f.cktext_area :body, value: @article.body %><br />

  <%= f.submit 'Post This Revision' %>
<% end %>

app/views/users/_login.html.erb
<%= form_tag '/sessions', html: { id: "login" }, remote: true, authenticity_token: true do %>
  <%= hidden_field_tag :errors, 'Invalid%20username%20or%20password' %>
  <%= text_field_tag :username, nil, placeholder: "username" %>
  <%= password_field_tag :password, nil, placeholder: "password" %>
  <%= submit_tag "Login" %>

<% end %>

app/views/users/new.html.erb
<%= render 'sessions/errors' %>

<%= form_for @user, url: { action: "create"}, html: { id: "new-user-form"} do |f|  %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.submit "Register" %>
<% end %>

app/views/welcome/_login.html.erb
<%= form_tag '/sessions', html: { id: "login" } do %>

  <%= text_field_tag :username, nil, placeholder: "username" %>
  <%= password_field_tag :password, nil, placeholder: "password" %>
  <%= submit_tag "Login" %>

<% end %>

app/views/welcome/index.html.erb
<div id="container">
  <div id="home-cat-display">
    <div class='search'>
 <%= form_tag(search_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Articles" %>
    <%= submit_tag "Search", :name => nil %>
<% end %> </div>
  <h1><%= link_to 'Categories', categories_path %></h1>
    <div id='category-list'>

      <% if @categories.any?  %>
        <% @categories.each do |cat| %>
          <span><%= link_to cat.name, category_path(cat) %><br></span>
        <% end %>
      </div>
    <% end %>
  </div>

  <div id="home-art-display">
    <h1><%= link_to 'Articles', articles_path %></h1>
    <div id='articles-list'>
      <% if @articles.any?  %>
        <% @articles.each do |art| %>

           <% if art.thumbnail %> <img src="<%=art.thumbnail%>" style="width:100px;height:100px;dispaly:inline-block"> <% else %> <img src="https://raw.githubusercontent.com/TylerSmall19/cotton-tales/NoahRGuy-logo/logo.png" style="width:100px;height:100px"> <% end %> <span><%= link_to art.title, article_path(art) %><br>
          <%= art.shorten %>
          </span><br><br>
        <% end %>
      </div>
    <% end %>
  </div>
</div>